# Generated by fusen: do not edit by hand

#' Check data integrity
#'
#' @param dataset Dataset to check the integrity
#'
#' @return Side effect: Display message in the command to say if the data integrity is OK or not 
#' @export
#'
#' @examples
#' datafile <- system.file("nyc_squirrels_sample.csv", package = "checkdataanme")
#' nyc_squirrels <- read.csv(datafile)
#' check_data_integrity(nyc_squirrels)
check_data_integrity <- function(dataset) {
 if(length(grep('\\+', dataset$primary_fur_color)) > 0){
    message('Not all values are color')
 }else{
   message('OK')
 }
}
